export interface OpportunityIntelligence {}
export interface OpportunityClassification {}
export interface CandidateMatch {}
export interface EligibilityAssessment {}
export interface MatchFactor {}
export interface MatchScore {}
export interface RankingResult {}
export interface Explanation {}
export interface IntelligenceRun {}
export interface IntelligenceStatus {}
