export enum OpportunityStatus {
  DISCOVERED = 'DISCOVERED',
  ACTIVE = 'ACTIVE',
  DEADLINE_APPROACHING = 'DEADLINE_APPROACHING',
  CLOSING_SOON = 'CLOSING_SOON',
  EXPIRED = 'EXPIRED',
  CLOSED = 'CLOSED',
  STALE = 'STALE',
  VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED',
}

export enum DeadlineType {
  FIXED = 'FIXED',
  ROLLING = 'ROLLING',
  UNKNOWN = 'UNKNOWN',
}

export enum EligibilityState {
  ELIGIBLE = 'ELIGIBLE',
  INELIGIBLE = 'INELIGIBLE',
  UNCERTAIN = 'UNCERTAIN',
}

export enum DuplicateState {
  CANONICAL = 'CANONICAL',
  DUPLICATE = 'DUPLICATE',
  POSSIBLE_DUPLICATE = 'POSSIBLE_DUPLICATE',
}

export enum SkillRelationType {
  REQUIRED = 'REQUIRED',
  PREFERRED = 'PREFERRED',
}

export enum NotificationStatus {
  SCHEDULED = 'SCHEDULED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
  SMS = 'SMS',
  WEBHOOK = 'WEBHOOK',
}

export enum DeliveryStatus {
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
}

export enum OpportunityLifecycle {
  DISCOVERED = 'DISCOVERED',
  NORMALIZED = 'NORMALIZED',
  CLASSIFIED = 'CLASSIFIED',
  ELIGIBILITY_CHECK = 'ELIGIBILITY_CHECK',
  MATCHED = 'MATCHED',
  RANKED = 'RANKED',
  RECOMMENDED = 'RECOMMENDED',
  VIEWED = 'VIEWED',
  SAVED = 'SAVED',
  APPLICATION_TRACKING = 'APPLICATION_TRACKING',
}

export enum RemotePreference {
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
  ONSITE = 'ONSITE',
  FLEXIBLE = 'FLEXIBLE',
}

export enum RequirementType {
  DEGREE = 'DEGREE',
  ENROLLMENT_STATUS = 'ENROLLMENT_STATUS',
  CITIZENSHIP = 'CITIZENSHIP',
  WORK_AUTHORIZATION = 'WORK_AUTHORIZATION',
  LOCATION = 'LOCATION',
  EXPERIENCE = 'EXPERIENCE',
  AGE = 'AGE',
  ACADEMIC = 'ACADEMIC',
  SECURITY_CLEARANCE = 'SECURITY_CLEARANCE',
  OTHER = 'OTHER',
}
